/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AffiliateDisclosureRouteImport } from './routes/affiliate-disclosure'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiPrometheusRouteImport } from './routes/api/prometheus'
import { Route as DealSlugRouteImport } from './routes/deal.$slug'
import { Route as ApiAdminAmazonHydrateRouteImport } from './routes/api/admin/amazon-hydrate'
import { Route as ApiAdminAmazonRefreshRouteImport } from './routes/api/admin/amazon-refresh'
import { Route as ApiAdminAmazonSearchRouteImport } from './routes/api/admin/amazon-search'
import { Route as ApiAdminAmazonVariationsRouteImport } from './routes/api/admin/amazon-variations'
import { Route as ApiAdminFetchDetailsRouteImport } from './routes/api/admin/fetch-details'
import { Route as ApiPublicAmazonDiagnosticsRouteImport } from './routes/api/public/amazon-diagnostics'
import { Route as ApiPublicCronRefreshDealsRouteImport } from './routes/api/public/cron/refresh-deals'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateDisclosureRoute = AffiliateDisclosureRouteImport.update({
  id: '/affiliate-disclosure',
  path: '/affiliate-disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrometheusRoute = ApiPrometheusRouteImport.update({
  id: '/api/prometheus',
  path: '/api/prometheus',
  getParentRoute: () => rootRouteImport,
} as any)
const DealSlugRoute = DealSlugRouteImport.update({
  id: '/deal/$slug',
  path: '/deal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAmazonHydrateRoute = ApiAdminAmazonHydrateRouteImport.update({
  id: '/api/admin/amazon-hydrate',
  path: '/api/admin/amazon-hydrate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAmazonRefreshRoute = ApiAdminAmazonRefreshRouteImport.update({
  id: '/api/admin/amazon-refresh',
  path: '/api/admin/amazon-refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAmazonSearchRoute = ApiAdminAmazonSearchRouteImport.update({
  id: '/api/admin/amazon-search',
  path: '/api/admin/amazon-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAmazonVariationsRoute =
  ApiAdminAmazonVariationsRouteImport.update({
    id: '/api/admin/amazon-variations',
    path: '/api/admin/amazon-variations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminFetchDetailsRoute = ApiAdminFetchDetailsRouteImport.update({
  id: '/api/admin/fetch-details',
  path: '/api/admin/fetch-details',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAmazonDiagnosticsRoute =
  ApiPublicAmazonDiagnosticsRouteImport.update({
    id: '/api/public/amazon-diagnostics',
    path: '/api/public/amazon-diagnostics',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronRefreshDealsRoute =
  ApiPublicCronRefreshDealsRouteImport.update({
    id: '/api/public/cron/refresh-deals',
    path: '/api/public/cron/refresh-deals',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/affiliate-disclosure': typeof AffiliateDisclosureRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/api/prometheus': typeof ApiPrometheusRoute
  '/deal/$slug': typeof DealSlugRoute
  '/api/admin/amazon-hydrate': typeof ApiAdminAmazonHydrateRoute
  '/api/admin/amazon-refresh': typeof ApiAdminAmazonRefreshRoute
  '/api/admin/amazon-search': typeof ApiAdminAmazonSearchRoute
  '/api/admin/amazon-variations': typeof ApiAdminAmazonVariationsRoute
  '/api/admin/fetch-details': typeof ApiAdminFetchDetailsRoute
  '/api/public/amazon-diagnostics': typeof ApiPublicAmazonDiagnosticsRoute
  '/api/public/cron/refresh-deals': typeof ApiPublicCronRefreshDealsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/affiliate-disclosure': typeof AffiliateDisclosureRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/api/prometheus': typeof ApiPrometheusRoute
  '/deal/$slug': typeof DealSlugRoute
  '/api/admin/amazon-hydrate': typeof ApiAdminAmazonHydrateRoute
  '/api/admin/amazon-refresh': typeof ApiAdminAmazonRefreshRoute
  '/api/admin/amazon-search': typeof ApiAdminAmazonSearchRoute
  '/api/admin/amazon-variations': typeof ApiAdminAmazonVariationsRoute
  '/api/admin/fetch-details': typeof ApiAdminFetchDetailsRoute
  '/api/public/amazon-diagnostics': typeof ApiPublicAmazonDiagnosticsRoute
  '/api/public/cron/refresh-deals': typeof ApiPublicCronRefreshDealsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/affiliate-disclosure': typeof AffiliateDisclosureRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/api/prometheus': typeof ApiPrometheusRoute
  '/deal/$slug': typeof DealSlugRoute
  '/api/admin/amazon-hydrate': typeof ApiAdminAmazonHydrateRoute
  '/api/admin/amazon-refresh': typeof ApiAdminAmazonRefreshRoute
  '/api/admin/amazon-search': typeof ApiAdminAmazonSearchRoute
  '/api/admin/amazon-variations': typeof ApiAdminAmazonVariationsRoute
  '/api/admin/fetch-details': typeof ApiAdminFetchDetailsRoute
  '/api/public/amazon-diagnostics': typeof ApiPublicAmazonDiagnosticsRoute
  '/api/public/cron/refresh-deals': typeof ApiPublicCronRefreshDealsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/affiliate-disclosure'
    | '/auth'
    | '/compare'
    | '/contact'
    | '/disclaimer'
    | '/privacy'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/terms'
    | '/api/prometheus'
    | '/deal/$slug'
    | '/api/admin/amazon-hydrate'
    | '/api/admin/amazon-refresh'
    | '/api/admin/amazon-search'
    | '/api/admin/amazon-variations'
    | '/api/admin/fetch-details'
    | '/api/public/amazon-diagnostics'
    | '/api/public/cron/refresh-deals'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/affiliate-disclosure'
    | '/auth'
    | '/compare'
    | '/contact'
    | '/disclaimer'
    | '/privacy'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/terms'
    | '/api/prometheus'
    | '/deal/$slug'
    | '/api/admin/amazon-hydrate'
    | '/api/admin/amazon-refresh'
    | '/api/admin/amazon-search'
    | '/api/admin/amazon-variations'
    | '/api/admin/fetch-details'
    | '/api/public/amazon-diagnostics'
    | '/api/public/cron/refresh-deals'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/affiliate-disclosure'
    | '/auth'
    | '/compare'
    | '/contact'
    | '/disclaimer'
    | '/privacy'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/terms'
    | '/api/prometheus'
    | '/deal/$slug'
    | '/api/admin/amazon-hydrate'
    | '/api/admin/amazon-refresh'
    | '/api/admin/amazon-search'
    | '/api/admin/amazon-variations'
    | '/api/admin/fetch-details'
    | '/api/public/amazon-diagnostics'
    | '/api/public/cron/refresh-deals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AffiliateDisclosureRoute: typeof AffiliateDisclosureRoute
  AuthRoute: typeof AuthRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  DisclaimerRoute: typeof DisclaimerRoute
  PrivacyRoute: typeof PrivacyRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ApiPrometheusRoute: typeof ApiPrometheusRoute
  DealSlugRoute: typeof DealSlugRoute
  ApiAdminAmazonHydrateRoute: typeof ApiAdminAmazonHydrateRoute
  ApiAdminAmazonRefreshRoute: typeof ApiAdminAmazonRefreshRoute
  ApiAdminAmazonSearchRoute: typeof ApiAdminAmazonSearchRoute
  ApiAdminAmazonVariationsRoute: typeof ApiAdminAmazonVariationsRoute
  ApiAdminFetchDetailsRoute: typeof ApiAdminFetchDetailsRoute
  ApiPublicAmazonDiagnosticsRoute: typeof ApiPublicAmazonDiagnosticsRoute
  ApiPublicCronRefreshDealsRoute: typeof ApiPublicCronRefreshDealsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate-disclosure': {
      id: '/affiliate-disclosure'
      path: '/affiliate-disclosure'
      fullPath: '/affiliate-disclosure'
      preLoaderRoute: typeof AffiliateDisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prometheus': {
      id: '/api/prometheus'
      path: '/api/prometheus'
      fullPath: '/api/prometheus'
      preLoaderRoute: typeof ApiPrometheusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deal/$slug': {
      id: '/deal/$slug'
      path: '/deal/$slug'
      fullPath: '/deal/$slug'
      preLoaderRoute: typeof DealSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/amazon-hydrate': {
      id: '/api/admin/amazon-hydrate'
      path: '/api/admin/amazon-hydrate'
      fullPath: '/api/admin/amazon-hydrate'
      preLoaderRoute: typeof ApiAdminAmazonHydrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/amazon-refresh': {
      id: '/api/admin/amazon-refresh'
      path: '/api/admin/amazon-refresh'
      fullPath: '/api/admin/amazon-refresh'
      preLoaderRoute: typeof ApiAdminAmazonRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/amazon-search': {
      id: '/api/admin/amazon-search'
      path: '/api/admin/amazon-search'
      fullPath: '/api/admin/amazon-search'
      preLoaderRoute: typeof ApiAdminAmazonSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/amazon-variations': {
      id: '/api/admin/amazon-variations'
      path: '/api/admin/amazon-variations'
      fullPath: '/api/admin/amazon-variations'
      preLoaderRoute: typeof ApiAdminAmazonVariationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/fetch-details': {
      id: '/api/admin/fetch-details'
      path: '/api/admin/fetch-details'
      fullPath: '/api/admin/fetch-details'
      preLoaderRoute: typeof ApiAdminFetchDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/amazon-diagnostics': {
      id: '/api/public/amazon-diagnostics'
      path: '/api/public/amazon-diagnostics'
      fullPath: '/api/public/amazon-diagnostics'
      preLoaderRoute: typeof ApiPublicAmazonDiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/refresh-deals': {
      id: '/api/public/cron/refresh-deals'
      path: '/api/public/cron/refresh-deals'
      fullPath: '/api/public/cron/refresh-deals'
      preLoaderRoute: typeof ApiPublicCronRefreshDealsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AffiliateDisclosureRoute: AffiliateDisclosureRoute,
  AuthRoute: AuthRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  DisclaimerRoute: DisclaimerRoute,
  PrivacyRoute: PrivacyRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ApiPrometheusRoute: ApiPrometheusRoute,
  DealSlugRoute: DealSlugRoute,
  ApiAdminAmazonHydrateRoute: ApiAdminAmazonHydrateRoute,
  ApiAdminAmazonRefreshRoute: ApiAdminAmazonRefreshRoute,
  ApiAdminAmazonSearchRoute: ApiAdminAmazonSearchRoute,
  ApiAdminAmazonVariationsRoute: ApiAdminAmazonVariationsRoute,
  ApiAdminFetchDetailsRoute: ApiAdminFetchDetailsRoute,
  ApiPublicAmazonDiagnosticsRoute: ApiPublicAmazonDiagnosticsRoute,
  ApiPublicCronRefreshDealsRoute: ApiPublicCronRefreshDealsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
